---
 - name: testing host variables
   hosts: all
   vars:
          user: dinesh
          pkg: mariadb
   tasks:
           - name: create  user {{ user }}
             user:
              name: '{{ user }}'
              state: present

           - name: installing package {{ pkg }}
             yum:         
              name: '{{ pkg }}'
              state: present       


