---
 - name: test conditions
   hosts: all
   vars:
           os:
                   - RedHat
                   - fedora
                   - suse
                   - CentOS

  
   tasks:
           - name: install packages on {{ os }} specified disrtibution
             yum:
                     name: postfix
                     state: present
             when: ansible_distribution in os       
           
